### ISSUE TITLE
Recycling page show blue box instead of context

### ISSUE THREAD

**Issue by grecine** [rutherford-nj/www.rutherford-nj.com#349]
Issue: The URL https://www.rutherfordboronj.com/departments/public-works/recycling-information/ shows a blue box instead of the information it's supposed to show.

How to reproduce: Go to the URL and you should see a blue box.

Info: macOS Big Sur, using both Safari 15.0 and Chrome 94.0.4606.81 (contact blockers and ad blockers off). Also on iOS 15.0.2 using Safari

The image below is from Chrome:

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/2029941/137608341-c7e6745d-6ddf-4b7e-a47c-0495a2d98a68.png">

**Comment by bogosj** [comment]
The third party who hosts this appears to have fixed it?

![image](https://user-images.githubusercontent.com/10186620/137633423-58a96e30-4c6b-4522-871c-fafd2d54d5ca.png)

Can you confirm?

**Comment by grecine** [comment]
Confirmed. PMFI I guess
